"""Core modules for Gemini Omni MCP."""

from .exceptions import (
    APIError,
    AuthenticationError,
    ConfigurationError,
    ContentPolicyError,
    FileOperationError,
    RateLimitError,
    UltimateGeminiError,
    ValidationError,
    VideoProcessingError,
)
from .validation import (
    coerce_image_paths,
    sanitize_filename,
    validate_base64_image,
    validate_batch_size,
    validate_delivery,
    validate_duration_seconds,
    validate_file_path,
    validate_input_video,
    validate_model,
    validate_prompt,
    validate_prompts_list,
    validate_reference_image,
    validate_reference_images_count,
    validate_task,
    validate_video_aspect_ratio,
)

__all__ = [
    "UltimateGeminiError",
    "ConfigurationError",
    "ValidationError",
    "APIError",
    "AuthenticationError",
    "RateLimitError",
    "ContentPolicyError",
    "VideoProcessingError",
    "FileOperationError",
    "coerce_image_paths",
    "validate_prompt",
    "validate_model",
    "validate_video_aspect_ratio",
    "validate_task",
    "validate_duration_seconds",
    "validate_delivery",
    "validate_file_path",
    "validate_input_video",
    "validate_base64_image",
    "validate_prompts_list",
    "validate_batch_size",
    "validate_reference_image",
    "validate_reference_images_count",
    "sanitize_filename",
]
